// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (folder_id, name, description)
SELECT f.id, $1, $2
FROM folders f
WHERE f.id = $3 AND f.owner_id = $4
RETURNING id, folder_id, name, description, created_at, updated_at
`

type CreateDeckParams struct {
	Name        string
	Description string
	FolderID    uuid.UUID
	OwnerID     uuid.UUID
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.Name,
		arg.Description,
		arg.FolderID,
		arg.OwnerID,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :execrows
DELETE FROM decks d
USING folders f
WHERE d.folder_id = f.id AND d.id = $1 AND f.owner_id = $2
`

type DeleteDeckParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteDeck(ctx context.Context, arg DeleteDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeck, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeck = `-- name: GetDeck :one
SELECT
    d.id, d.folder_id, d.name, d.description, d.created_at, d.updated_at,
    (SELECT count(*) FROM flashcards fc WHERE fc.deck_id = d.id)::int AS card_count
FROM decks d
JOIN folders f ON f.id = d.folder_id
WHERE d.id = $1 AND f.owner_id = $2
`

type GetDeckParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

type GetDeckRow struct {
	ID          uuid.UUID
	FolderID    uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CardCount   int32
}

func (q *Queries) GetDeck(ctx context.Context, arg GetDeckParams) (GetDeckRow, error) {
	row := q.db.QueryRow(ctx, getDeck, arg.ID, arg.OwnerID)
	var i GetDeckRow
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardCount,
	)
	return i, err
}

const listDecks = `-- name: ListDecks :many
SELECT
    d.id, d.folder_id, d.name, d.description, d.created_at, d.updated_at,
    (SELECT count(*) FROM flashcards fc WHERE fc.deck_id = d.id)::int AS card_count
FROM decks d
JOIN folders f ON f.id = d.folder_id
WHERE d.folder_id = $1 AND f.owner_id = $2
ORDER BY d.created_at ASC
`

type ListDecksParams struct {
	FolderID uuid.UUID
	OwnerID  uuid.UUID
}

type ListDecksRow struct {
	ID          uuid.UUID
	FolderID    uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CardCount   int32
}

func (q *Queries) ListDecks(ctx context.Context, arg ListDecksParams) ([]ListDecksRow, error) {
	rows, err := q.db.Query(ctx, listDecks, arg.FolderID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDecksRow{}
	for rows.Next() {
		var i ListDecksRow
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE decks d
SET name = $1,
    description = $2,
    updated_at = now()
FROM folders f
WHERE d.folder_id = f.id AND d.id = $3 AND f.owner_id = $4
RETURNING
    d.id, d.folder_id, d.name, d.description, d.created_at, d.updated_at,
    (SELECT count(*) FROM flashcards fc WHERE fc.deck_id = d.id)::int AS card_count
`

type UpdateDeckParams struct {
	Name        string
	Description string
	ID          uuid.UUID
	OwnerID     uuid.UUID
}

type UpdateDeckRow struct {
	ID          uuid.UUID
	FolderID    uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CardCount   int32
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (UpdateDeckRow, error) {
	row := q.db.QueryRow(ctx, updateDeck,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.OwnerID,
	)
	var i UpdateDeckRow
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CardCount,
	)
	return i, err
}
