// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flashcards.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createFlashcard = `-- name: CreateFlashcard :one
INSERT INTO flashcards (deck_id, front, back, position)
SELECT
    d.id,
    $1,
    $2,
    COALESCE((SELECT max(fc.position) + 1 FROM flashcards fc WHERE fc.deck_id = d.id), 0)
FROM decks d
JOIN folders f ON f.id = d.folder_id
WHERE d.id = $3 AND f.owner_id = $4
RETURNING id, deck_id, front, back, position, created_at, updated_at
`

type CreateFlashcardParams struct {
	Front   string
	Back    string
	DeckID  uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) CreateFlashcard(ctx context.Context, arg CreateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRow(ctx, createFlashcard,
		arg.Front,
		arg.Back,
		arg.DeckID,
		arg.OwnerID,
	)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlashcard = `-- name: DeleteFlashcard :execrows
DELETE FROM flashcards fc
USING decks d, folders f
WHERE fc.deck_id = d.id AND d.folder_id = f.id AND fc.id = $1 AND f.owner_id = $2
`

type DeleteFlashcardParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteFlashcard(ctx context.Context, arg DeleteFlashcardParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlashcard, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFlashcard = `-- name: GetFlashcard :one
SELECT fc.id, fc.deck_id, fc.front, fc.back, fc.position, fc.created_at, fc.updated_at
FROM flashcards fc
JOIN decks d ON d.id = fc.deck_id
JOIN folders f ON f.id = d.folder_id
WHERE fc.id = $1 AND f.owner_id = $2
`

type GetFlashcardParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetFlashcard(ctx context.Context, arg GetFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRow(ctx, getFlashcard, arg.ID, arg.OwnerID)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlashcards = `-- name: ListFlashcards :many
SELECT fc.id, fc.deck_id, fc.front, fc.back, fc.position, fc.created_at, fc.updated_at
FROM flashcards fc
JOIN decks d ON d.id = fc.deck_id
JOIN folders f ON f.id = d.folder_id
WHERE fc.deck_id = $1 AND f.owner_id = $2
ORDER BY fc.position ASC
`

type ListFlashcardsParams struct {
	DeckID  uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) ListFlashcards(ctx context.Context, arg ListFlashcardsParams) ([]Flashcard, error) {
	rows, err := q.db.Query(ctx, listFlashcards, arg.DeckID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flashcard{}
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlashcard = `-- name: UpdateFlashcard :one
UPDATE flashcards fc
SET front = $1,
    back = $2,
    position = $3,
    updated_at = now()
FROM decks d
JOIN folders f ON f.id = d.folder_id
WHERE fc.deck_id = d.id AND fc.id = $4 AND f.owner_id = $5
RETURNING fc.id, fc.deck_id, fc.front, fc.back, fc.position, fc.created_at, fc.updated_at
`

type UpdateFlashcardParams struct {
	Front    string
	Back     string
	Position int32
	ID       uuid.UUID
	OwnerID  uuid.UUID
}

func (q *Queries) UpdateFlashcard(ctx context.Context, arg UpdateFlashcardParams) (Flashcard, error) {
	row := q.db.QueryRow(ctx, updateFlashcard,
		arg.Front,
		arg.Back,
		arg.Position,
		arg.ID,
		arg.OwnerID,
	)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
