// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (owner_id, name)
VALUES ($1, $2)
RETURNING id, owner_id, name, created_at, updated_at
`

type CreateFolderParams struct {
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.OwnerID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders
WHERE id = $1 AND owner_id = $2
`

type DeleteFolderParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) error {
	_, err := q.db.Exec(ctx, deleteFolder, arg.ID, arg.OwnerID)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, owner_id, name, created_at, updated_at FROM folders
WHERE id = $1 AND owner_id = $2
`

type GetFolderParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetFolder(ctx context.Context, arg GetFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, arg.ID, arg.OwnerID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFolders = `-- name: ListFolders :many
SELECT id, owner_id, name, created_at, updated_at FROM folders
WHERE owner_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListFolders(ctx context.Context, ownerID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolders, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders
SET name = $3,
    updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, created_at, updated_at
`

type UpdateFolderParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolder, arg.ID, arg.OwnerID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
