// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CardReview struct {
	ID            uuid.UUID
	CardID        uuid.UUID
	OwnerID       uuid.UUID
	Rating        int16
	StateBefore   int16
	ElapsedDays   float64
	Stability     float64
	Difficulty    float64
	ScheduledDays float64
	ReviewedAt    pgtype.Timestamptz
}

type CardReviewState struct {
	CardID         uuid.UUID
	OwnerID        uuid.UUID
	State          int16
	DueAt          pgtype.Timestamptz
	Stability      float64
	Difficulty     float64
	Reps           int32
	Lapses         int32
	LastReviewedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Deck struct {
	ID          uuid.UUID
	FolderID    uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Flashcard struct {
	ID        uuid.UUID
	DeckID    uuid.UUID
	Front     string
	Back      string
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Folder struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	GoogleSubject string
	Email         string
	DisplayName   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
