// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Deck struct {
	ID          uuid.UUID
	FolderID    uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Flashcard struct {
	ID        uuid.UUID
	DeckID    uuid.UUID
	Front     string
	Back      string
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Folder struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	GoogleSubject string
	Email         string
	DisplayName   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
