// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: study.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDueByDeck = `-- name: CountDueByDeck :many
SELECT fc.deck_id, count(*)::int AS due
FROM card_review_states crs
JOIN flashcards fc ON fc.id = crs.card_id
WHERE crs.owner_id = $1 AND crs.due_at <= $2
GROUP BY fc.deck_id
`

type CountDueByDeckParams struct {
	OwnerID uuid.UUID
	AsOf    pgtype.Timestamptz
}

type CountDueByDeckRow struct {
	DeckID uuid.UUID
	Due    int32
}

func (q *Queries) CountDueByDeck(ctx context.Context, arg CountDueByDeckParams) ([]CountDueByDeckRow, error) {
	rows, err := q.db.Query(ctx, countDueByDeck, arg.OwnerID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDueByDeckRow{}
	for rows.Next() {
		var i CountDueByDeckRow
		if err := rows.Scan(&i.DeckID, &i.Due); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDueTotal = `-- name: CountDueTotal :one
SELECT count(*)::int
FROM card_review_states
WHERE owner_id = $1 AND due_at <= $2
`

type CountDueTotalParams struct {
	OwnerID uuid.UUID
	AsOf    pgtype.Timestamptz
}

func (q *Queries) CountDueTotal(ctx context.Context, arg CountDueTotalParams) (int32, error) {
	row := q.db.QueryRow(ctx, countDueTotal, arg.OwnerID, arg.AsOf)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countNewByDeck = `-- name: CountNewByDeck :many
SELECT fc.deck_id, count(*)::int AS new
FROM flashcards fc
JOIN decks d ON d.id = fc.deck_id
JOIN folders f ON f.id = d.folder_id
LEFT JOIN card_review_states crs ON crs.card_id = fc.id
WHERE f.owner_id = $1 AND crs.card_id IS NULL
GROUP BY fc.deck_id
`

type CountNewByDeckRow struct {
	DeckID uuid.UUID
	New    int32
}

func (q *Queries) CountNewByDeck(ctx context.Context, ownerID uuid.UUID) ([]CountNewByDeckRow, error) {
	rows, err := q.db.Query(ctx, countNewByDeck, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNewByDeckRow{}
	for rows.Next() {
		var i CountNewByDeckRow
		if err := rows.Scan(&i.DeckID, &i.New); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNewTotal = `-- name: CountNewTotal :one
SELECT count(*)::int
FROM flashcards fc
JOIN decks d ON d.id = fc.deck_id
JOIN folders f ON f.id = d.folder_id
LEFT JOIN card_review_states crs ON crs.card_id = fc.id
WHERE f.owner_id = $1 AND crs.card_id IS NULL
`

func (q *Queries) CountNewTotal(ctx context.Context, ownerID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countNewTotal, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countReviewsSince = `-- name: CountReviewsSince :one
SELECT count(*)::int
FROM card_reviews
WHERE owner_id = $1 AND reviewed_at >= $2
`

type CountReviewsSinceParams struct {
	OwnerID uuid.UUID
	Since   pgtype.Timestamptz
}

func (q *Queries) CountReviewsSince(ctx context.Context, arg CountReviewsSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReviewsSince, arg.OwnerID, arg.Since)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getCardReviewState = `-- name: GetCardReviewState :one
SELECT card_id, owner_id, state, due_at, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
FROM card_review_states
WHERE card_id = $1 AND owner_id = $2
`

type GetCardReviewStateParams struct {
	CardID  uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetCardReviewState(ctx context.Context, arg GetCardReviewStateParams) (CardReviewState, error) {
	row := q.db.QueryRow(ctx, getCardReviewState, arg.CardID, arg.OwnerID)
	var i CardReviewState
	err := row.Scan(
		&i.CardID,
		&i.OwnerID,
		&i.State,
		&i.DueAt,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCardReview = `-- name: InsertCardReview :exec
INSERT INTO card_reviews (
    card_id, owner_id, rating, state_before, elapsed_days, stability, difficulty, scheduled_days
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertCardReviewParams struct {
	CardID        uuid.UUID
	OwnerID       uuid.UUID
	Rating        int16
	StateBefore   int16
	ElapsedDays   float64
	Stability     float64
	Difficulty    float64
	ScheduledDays float64
}

func (q *Queries) InsertCardReview(ctx context.Context, arg InsertCardReviewParams) error {
	_, err := q.db.Exec(ctx, insertCardReview,
		arg.CardID,
		arg.OwnerID,
		arg.Rating,
		arg.StateBefore,
		arg.ElapsedDays,
		arg.Stability,
		arg.Difficulty,
		arg.ScheduledDays,
	)
	return err
}

const listDueCards = `-- name: ListDueCards :many
SELECT fc.id, fc.deck_id, fc.front, fc.back, fc.position, fc.created_at, fc.updated_at
FROM card_review_states crs
JOIN flashcards fc ON fc.id = crs.card_id
WHERE crs.owner_id = $1 AND crs.due_at <= $2
ORDER BY crs.due_at ASC
LIMIT $3
`

type ListDueCardsParams struct {
	OwnerID uuid.UUID
	AsOf    pgtype.Timestamptz
	Lim     int32
}

func (q *Queries) ListDueCards(ctx context.Context, arg ListDueCardsParams) ([]Flashcard, error) {
	rows, err := q.db.Query(ctx, listDueCards, arg.OwnerID, arg.AsOf, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flashcard{}
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCardsInDeck = `-- name: ListDueCardsInDeck :many
SELECT fc.id, fc.deck_id, fc.front, fc.back, fc.position, fc.created_at, fc.updated_at
FROM card_review_states crs
JOIN flashcards fc ON fc.id = crs.card_id
WHERE crs.owner_id = $1 AND crs.due_at <= $2 AND fc.deck_id = $3
ORDER BY crs.due_at ASC
LIMIT $4
`

type ListDueCardsInDeckParams struct {
	OwnerID uuid.UUID
	AsOf    pgtype.Timestamptz
	DeckID  uuid.UUID
	Lim     int32
}

func (q *Queries) ListDueCardsInDeck(ctx context.Context, arg ListDueCardsInDeckParams) ([]Flashcard, error) {
	rows, err := q.db.Query(ctx, listDueCardsInDeck,
		arg.OwnerID,
		arg.AsOf,
		arg.DeckID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flashcard{}
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewCards = `-- name: ListNewCards :many
SELECT fc.id, fc.deck_id, fc.front, fc.back, fc.position, fc.created_at, fc.updated_at
FROM flashcards fc
JOIN decks d ON d.id = fc.deck_id
JOIN folders f ON f.id = d.folder_id
LEFT JOIN card_review_states crs ON crs.card_id = fc.id
WHERE f.owner_id = $1 AND crs.card_id IS NULL
ORDER BY fc.created_at ASC, fc.position ASC
LIMIT $2
`

type ListNewCardsParams struct {
	OwnerID uuid.UUID
	Lim     int32
}

func (q *Queries) ListNewCards(ctx context.Context, arg ListNewCardsParams) ([]Flashcard, error) {
	rows, err := q.db.Query(ctx, listNewCards, arg.OwnerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flashcard{}
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewCardsInDeck = `-- name: ListNewCardsInDeck :many
SELECT fc.id, fc.deck_id, fc.front, fc.back, fc.position, fc.created_at, fc.updated_at
FROM flashcards fc
JOIN decks d ON d.id = fc.deck_id
JOIN folders f ON f.id = d.folder_id
LEFT JOIN card_review_states crs ON crs.card_id = fc.id
WHERE f.owner_id = $1 AND crs.card_id IS NULL AND fc.deck_id = $2
ORDER BY fc.position ASC
LIMIT $3
`

type ListNewCardsInDeckParams struct {
	OwnerID uuid.UUID
	DeckID  uuid.UUID
	Lim     int32
}

func (q *Queries) ListNewCardsInDeck(ctx context.Context, arg ListNewCardsInDeckParams) ([]Flashcard, error) {
	rows, err := q.db.Query(ctx, listNewCardsInDeck, arg.OwnerID, arg.DeckID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flashcard{}
	for rows.Next() {
		var i Flashcard
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewDays = `-- name: ListReviewDays :many
SELECT DISTINCT (reviewed_at AT TIME ZONE 'UTC')::date AS day
FROM card_reviews
WHERE owner_id = $1
ORDER BY day DESC
LIMIT 400
`

func (q *Queries) ListReviewDays(ctx context.Context, ownerID uuid.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listReviewDays, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCardReviewState = `-- name: UpsertCardReviewState :one
INSERT INTO card_review_states (
    card_id, owner_id, state, due_at, stability, difficulty, reps, lapses, last_reviewed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (card_id) DO UPDATE SET
    state = EXCLUDED.state,
    due_at = EXCLUDED.due_at,
    stability = EXCLUDED.stability,
    difficulty = EXCLUDED.difficulty,
    reps = EXCLUDED.reps,
    lapses = EXCLUDED.lapses,
    last_reviewed_at = EXCLUDED.last_reviewed_at,
    updated_at = now()
RETURNING card_id, owner_id, state, due_at, stability, difficulty, reps, lapses, last_reviewed_at, created_at, updated_at
`

type UpsertCardReviewStateParams struct {
	CardID         uuid.UUID
	OwnerID        uuid.UUID
	State          int16
	DueAt          pgtype.Timestamptz
	Stability      float64
	Difficulty     float64
	Reps           int32
	Lapses         int32
	LastReviewedAt pgtype.Timestamptz
}

func (q *Queries) UpsertCardReviewState(ctx context.Context, arg UpsertCardReviewStateParams) (CardReviewState, error) {
	row := q.db.QueryRow(ctx, upsertCardReviewState,
		arg.CardID,
		arg.OwnerID,
		arg.State,
		arg.DueAt,
		arg.Stability,
		arg.Difficulty,
		arg.Reps,
		arg.Lapses,
		arg.LastReviewedAt,
	)
	var i CardReviewState
	err := row.Scan(
		&i.CardID,
		&i.OwnerID,
		&i.State,
		&i.DueAt,
		&i.Stability,
		&i.Difficulty,
		&i.Reps,
		&i.Lapses,
		&i.LastReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
