// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_subject, email, display_name)
VALUES ($1, $2, $3)
RETURNING id, google_subject, email, display_name, created_at, updated_at
`

type CreateUserParams struct {
	GoogleSubject string
	Email         string
	DisplayName   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.GoogleSubject, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSubject = `-- name: GetUserByGoogleSubject :one
SELECT id, google_subject, email, display_name, created_at, updated_at FROM users
WHERE google_subject = $1
`

func (q *Queries) GetUserByGoogleSubject(ctx context.Context, googleSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSubject, googleSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_subject, email, display_name, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = $2,
    display_name = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, google_subject, email, display_name, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByGoogleSubject = `-- name: UpsertUserByGoogleSubject :one
INSERT INTO users (google_subject, email, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (google_subject)
DO UPDATE SET
    email = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    updated_at = now()
RETURNING id, google_subject, email, display_name, created_at, updated_at
`

type UpsertUserByGoogleSubjectParams struct {
	GoogleSubject string
	Email         string
	DisplayName   string
}

func (q *Queries) UpsertUserByGoogleSubject(ctx context.Context, arg UpsertUserByGoogleSubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByGoogleSubject, arg.GoogleSubject, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
